name: vanira
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  carousel_slider: ^4.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/tourist_attractions/
  fonts:
  - family: Montserrat
    fonts:
    - asset: assets/fonts/Montserrat-SemiBold.ttf
    - asset: assets/fonts/Montserrat-Bold.ttf
    - asset: assets/fonts/Montserrat-Medium.ttf
    - asset: assets/fonts/Montserrat-Regular.ttf
